swagger: '2.0'
info:
  title: funkypassdev.azurewebsites.net
  version: 1.0.0
host: funkypassdev.azurewebsites.net
basePath: /
schemes:
  - https
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /api/GeneratePassword:
    get:
      operationId: /api/GeneratePassword/get
      parameters:
        - name: minlen
          in: query
          description: Minimum password length
          required: false
          type: integer
          default: 10 
        - name: lang
          in: query
          description: 'Language, list of languages /api/GetLang/get'
          required: false
          type: string
          default: "Random"
        - name: asciionly
          in: query
          description: Remove diacritics
          required: false
          type: boolean
          default: true
      description: Generates new random password based on selected dictionar
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
    post:
      operationId: /api/GeneratePassword/post
      parameters:
        - name: minlen
          in: query
          description: Minimum password length
          required: false
          type: integer
          default: 10
        - name: lang
          in: query
          description: 'Language, list of languages /api/GetLang/get'
          required: false
          type: string
          default: "Random"
        - name: asciionly
          in: query
          description: Remove diacritics
          required: false
          type: boolean
          default: true
      description: Generates new random password based on selected dictionary
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/GetLang:
    get:
      operationId: /api/GetLang/get
      description: Show all available languages
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
definitions: {}
securityDefinitions:
  apikeyQuery:
    type: apiKey
    name: code
    in: query
